### ISSUE TITLE
Moving STL to a separate package

### ISSUE THREAD

**Issue by guilhermebodin** [viraltux/Forecast.jl#49]
Hi, @viraltux very nice package that you are developing. 

I need the STL algorithm to perform seasonality differencing tests on an auto arima function that I am developing on StateSpaceModels.jl but I would not like to add the all Forecast.jl package as a dependency, in fact, I want to build a very lightweight package for STL. What do you think about having a separate STL package and adding it to your project?

If you wish I can do the transition.

**Comment by viraltux** [comment]
Hi @guilhermebodin, thanks for the kudos!

Okay, a few comments... actually you might be right on creating lightweight packages, but the new lightweight package we may need is not an STL one but a LOESS one (STL stands for Seasonal and Trend decomposition using **Loess**). Let me explain...

When I began working on STL to learn Julia I did not want to spend time coding LOESS so I thought about using the package [Loess.jl](https://github.com/JuliaStats/Loess.jl). Unfortunately, although the Loess.jl package is very fast it has a severe limitation; it cannot extrapolate. In their code you can read 

> "Loess (or at least most implementations, including this one), does not perform extrapolation". 

This statement might not be quite accurate since there is no way to implement STL as described in the original paper without extrapolating LOESS. Loess.jl is based on this [paper](https://link.springer.com/article/10.1007/BF01890836) and uses the ak-d tree implementation with the caveat mentioned before.

At this stage these were my options to have extrapolated LOESS for STL:

1. Fix the ak-d tree implementation in Loess.jl
2. Code one of the other methods in the paper (I believe the third degree-of-freedom approximation allows you to trade speed for accuracy)
3. Implement exact Loess; slow but precise.

Option 1. Might take a lot of researching and little coding and I was trying to learn Julia, besides, the paper is behind a paywall so I discarded this option.
Option 2. Paper still paywalled and I wanted to work on STL and, anyway, all implementations are still fast **approximations**.

Therefore I end up implementing exact Loess as described in Cleveland STL original paper which is slow but for high eccentricity series provides much better results than fast approximations.  

Sorry for the long explanation but it was needed for me to suggest that instead using your time to create an STL package, which invariable will need Loess anyway, you might consider to go for options 1. and 2. and 3. and make the Loess.jl package one capable to extrapolate and one that allows us to trade off precision for speed.

**This is my advice;** If you have time fix the Loess.jl package then I myself will use it on Forecast.jl and I will update the STL function accordingly. At that point seems obvious that would not make much sense to create a full package just for STL since STL is rather a protocol based on LOESS and no implementation is going to be faster than other. Then you can add the Forecast stl.jl file to StateSpaceModels.jl since Forecast.jl has a MIT license, and you can adjust its protocol to your auto_arima needs (stl has many options). 

**However**, if you like myself don't have much time then, rather than building an STL package and since Forecast.jl and  StateSpaceModels.jl are both MIT licensed, I would suggest to simply take stl.jl and loess.jl from Forecast.jl, add them to  StateSpaceModels.jl and call it a day!

 Anyway these are my two cents... maybe five dollars given the length of the answer! your choice.

**Comment by guilhermebodin** [comment]
Hi, @viraltux Thank you for the clear explanation.

For now, I decided to publish a v0.1.0 of the code on STL.jl stl.jl and Loess.jl that requires minimal dependencies (https://github.com/JuliaRegistries/General/pull/38620). My idea for making a separate STL package is based on the fact that STL is handy, and many times people only need this particular method in their framework.

I understand that it would make even more sense to update the Loess.jl package and leave people to design their own STL protocol. I am going to investigate this option a little deeper this week.

**Comment by viraltux** [comment]
Sure, whatever work best for you guys. Actually I myself envision Forecast.jl mainly as a future metapackage handling other packages. For instance a package with smoothers like loess (perhaps with its own package) , hma and others, then another package for time series decomposition with STL and others, etc. 

Good luck Guilherme!
